stages:
    - validation
    - test_php74

variables:
    MYSQL_DATABASE: "skeleton4"
    MYSQL_ROOT_PASSWORD: "supersecret"
    DATABASE_URL: "mysql://root:supersecret@mysql:3306/skeleton4"
    COMPOSER_CACHE_DIR: "/cache/php-composer"
    NPM_CONFIG_CACHE: "/cache/node-npm"
    BUNDLE_PATH: "/cache/ruby-gems"
    SECURITY_CHECKER: "https://api.github.com/repos/fabpot/local-php-security-checker/releases/latest"
    POSTGRES_DB: "app_testing"
    POSTGRES_USER: "runner"
    POSTGRES_PASSWORD: "supersecret"
    POSTGRES_HOST_AUTH_METHOD: trust

before_script:
    - rm -f /usr/local/etc/php/conf.d/xdebug.ini
    - echo 'date.timezone=Europe/Moscow' >> /usr/local/etc/php/conf.d/extra.ini
    - echo 'memory_limit = 2G' >> /usr/local/etc/php/conf.d/extra.ini
    - sudo chown -R www-data:www-data ./

validation_check:
    stage: validation
    image: vziks/php-common:7.4
    services:
        - mysql:5.7
    allow_failure: false
    dependencies: [ ]
    script:
        - composer install --profile --prefer-dist --no-interaction --no-scripts
        - composer validate
        - bin/console doctrine:schema:validate --skip-sync
    cache:
        key: ${CI_PROJECT_PATH_SLUG}
        paths:
            - vendor/

security_check:
    stage: validation
    image: vziks/php-common:7.4
    allow_failure: true
    dependencies: [ ]
    script:
        - curl -s $SECURITY_CHECKER | grep "linux_386" | grep "browser_download_url" | curl -L -o local-php-security-checker $(cut -d '"' -f 4)
        - chmod +x 'local-php-security-checker'
        - ./local-php-security-checker
    cache: { }

codestyle_check:
    stage: validation
    image: vziks/php-common:7.4
    allow_failure: true
    dependencies: [ ]
    script:
        - composer install --profile --prefer-dist --no-interaction --no-scripts
        - PHP_CS_FIXER_FUTURE_MODE=1 php ./vendor/bin/php-cs-fixer fix --dry-run -v --diff; echo $?
    cache: { }

.phpunit: &phpunit
    allow_failure: false
    script:
        - composer install --profile --prefer-dist -n
        - ./bin/setup-test.sh
        - ./bin/console doctrine:schema:validate -e test
        - ./vendor/bin/simple-phpunit -c phpunit.xml
    cache:
        key: ${CI_PROJECT_PATH_SLUG}
        policy: pull
        paths:
            - vendor/

#phpunit_74_psg12:
#    stage: test_php74
#    image: vziks/php-common:7.4
#    services:
#        - postgres:12.2-alpine
#    variables:
#        POSTGRES_DB: app_testing
#        POSTGRES_USER: runner
#        POSTGRES_PASSWORD: ''
#        POSTGRES_HOST_AUTH_METHOD: trust
#    <<: *phpunit

phpunit_74_57:
    stage: test_php74
    image: vziks/php-common:7.4
    services:
        - mysql:5.7
    <<: *phpunit